export const apikey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1Y29kbndrcGdxaXpibHltdWN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTA3NTE2MzEsImV4cCI6MjAyNjMyNzYzMX0.MLNk6YmiGznEuXfhBhKjE8KtPPvGCPoQD4ZSJlV95k8";
export const endpoint =
  "https://uucodnwkpgqizblymucy.supabase.co/rest/v1/recipes";
